### ISSUE TITLE
How to use this with Portainer stacks ?

### ISSUE THREAD

**Issue by Nindohana** [LooLzzz/docking-station#23]
Hello,
Awesome software, I can't seem to make it work via portainer use of stacks currently, is there a workaround or are those two solutions not working together at all?

**Comment by laalauren1** [comment]
> Hello,
> Awesome software, I can't seem to make it work via portainer use of stacks currently, is there a workaround or are those two solutions not working together at all?

@Nindohana  It seems like you're having trouble getting the software to work with Portainer stacks.

**Comment by Nindohana** [comment]
Yes exactly, did you manage to make it works?

**Comment by laalauren1** [comment]
@Nindohana I haven't personally tried that setup. You might need to troubleshoot with the support team for a solution.
I'll have to refer you to the official support live chat with the ticket ID STA07638
Please see the link below to our dedicated support line:
[Stacks Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by LooLzzz** [comment]
As mentioned in the [Installation section](https://github.com/LooLzzz/docking-station#using-docker-compose-recommended)

> \# you should add mount points for each containers' docker-compose file you intend on update using this tool
> \# i usually put everything in a single neat folder under
> \# ⚠️ left stacks path == right stacks path (MUST)

You need to make sure you mount to same path as portainer does,  
according to this [link](https://www.reddit.com/r/portainer/comments/xc58i8/noob_question_where_can_i_find_the/),  
it's located at `/data/compose/` in the portainer container
