### ISSUE TITLE
"Short" image declaration causes "Keyerror"

### ISSUE THREAD

**Issue by ShanDestromp** [LooLzzz/docking-station#54]
Related (presumably) to #35.  In my case simply deleting the `@sha256:......` wasn't enough to make the error go away; despite clean installs of `DS`.  It turns out my compose file was old enough that the image declarations for `redis` and `postgres` were in the abbreviated form, opposed to the `host/developer/app` style that `Immich` currently uses.

That is to say I had

`image: tensorchord/pgvecto-rs:pg14-v0.2.0`

instead of `image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0`

I'm not sure why specifically those are an issue as I have many other containers that are in the simple `image: developer/app` format without issue, although offhand I don't recall if any other "short form" declarations also include a specific version.

**Comment by LooLzzz** [comment]
It really shouldn't matter whether you use `tensorchord/pgvecto-rs:pg14-v0.2.0` or `docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0`

It's passed on to `regctl` to fetch the latest image stuff,
and some reason it doesn't know how to handle `docker.io/...` stuff.

I've re-opened #35, and I'll keep working on it.

Thank you for the detailed issue here!

**Comment by LooLzzz** [comment]
Closed in favor of #35
